name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0-beta1
        stable: false

    - name: Env
      run: go env -w GOPRIVATE=github.com/veyronifs/*

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
